Repository go-vela/cli, pull requests merged in 2019-12, with the labels that each got.

#29 Uptick version for new release
  version/version.go
Labels: bug

#30 Release v0.2.0-rc2
  go.mod
  go.sum
Labels: enhancement

#32 chore: update all go mod dependencies
  .github/workflows/validate.yml
  go.mod
  go.sum
  makefile
Labels: enhancement

#33 chore: update go-vela dependencies
  go.mod
  go.sum
Labels: enhancement

#34 ci: update event trigger for prerelease
  .github/workflows/prerelease.yml
Labels: bug

#35 ci: switch from coveralls to codecov
  .github/README.md
  .github/workflows/test.yml
Labels: enhancement

#36 ci: add explicit configuration for automation
  .golangci.yml
  codecov.yml
Labels: enhancement

#37 refactor: fix linter errors
  cmd/config/gen.go
  cmd/config/remove.go
  cmd/config/update.go
  cmd/config/view.go
  util/error.go
Labels: enhancement

#38 chore: update for v0.2.0
  go.mod
  go.sum
Labels: dependencies

#39 ci(linters): update funlen linter settings
  .golangci.yml
Labels: enhancement
