Repository go-vela/cli, pull requests merged in 2020-07, with the labels that each got.

#129 feat: add completion action and commands
  action/completion/bash.go
  action/completion/completion.go
  action/completion/doc.go
  action/completion/generate.go
  action/completion/generate_test.go
  action/completion/validate.go
  action/completion/validate_test.go
  action/completion/zsh.go
  action/completion_generate.go
  action/completion_generate_test.go
Labels: feature

#132 chore(action): add logging statements
  action/build/get.go
  action/build/restart.go
  action/build/table.go
  action/build/validate.go
  action/build/view.go
  action/completion/generate.go
  action/completion/validate.go
  action/config/generate.go
  action/config/remove.go
  action/config/update.go
  action/config/validate.go
  action/config/view.go
  action/deployment/add.go
  action/deployment/get.go
  action/deployment/table.go
  action/deployment/validate.go
  action/deployment/view.go
  action/hook/get.go
  action/hook/table.go
  action/hook/validate.go
  action/hook/view.go
  action/log/get.go
  action/log/validate.go
  action/log/view.go
  action/pipeline/generate.go
  action/pipeline/stage.go
  action/pipeline/step.go
  action/pipeline/validate.go
  action/repo/add.go
  action/repo/chown.go
  action/repo/get.go
  action/repo/remove.go
  action/repo/repair.go
  action/repo/table.go
  action/repo/update.go
  action/repo/validate.go
  action/repo/view.go
  action/secret/add.go
  action/secret/get.go
  action/secret/remove.go
  action/secret/table.go
  action/secret/update.go
  action/secret/validate.go
  action/secret/view.go
  action/service/get.go
  action/service/table.go
  action/service/validate.go
  action/service/view.go
  action/step/get.go
  action/step/table.go
  action/step/validate.go
  action/step/view.go
Labels: enhancement

#131 ci: refactor Makefile. improve linter setup. upgrade deps.
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .golangci.yml
  Makefile
  codecov.yml
  makefile
Labels: enhancement

#130 feat: add action subcommands
  cmd/vela-cli/add.go
  cmd/vela-cli/chown.go
  cmd/vela-cli/generate.go
  cmd/vela-cli/get.go
  cmd/vela-cli/remove.go
  cmd/vela-cli/repair.go
  cmd/vela-cli/restart.go
  cmd/vela-cli/update.go
  cmd/vela-cli/validate.go
  cmd/vela-cli/view.go
Labels: feature

#133 fix: using config file with CLI
  action/config/validate.go
  action/config/view.go
  action/config_generate.go
  action/config_generate_test.go
  action/config_remove.go
  action/config_remove_test.go
  action/config_update.go
  action/config_update_test.go
  action/config_view.go
  action/config_view_test.go
Labels: bug

#134 refactor: update main for refactored subcommands
  cmd/vela-cli/add.go
  cmd/vela-cli/chown.go
  cmd/vela-cli/generate.go
  cmd/vela-cli/get.go
  cmd/vela-cli/main.go
  cmd/vela-cli/remove.go
  cmd/vela-cli/repair.go
  cmd/vela-cli/restart.go
  cmd/vela-cli/update.go
  cmd/vela-cli/validate.go
  cmd/vela-cli/view.go
Labels: enhancement

#135 feat: add login action and commands
  action/action.go
  action/login.go
  action/login/doc.go
  action/login/login.go
  action/login/login_test.go
  action/login/prompt.go
  action/login/prompt_test.go
  action/login/validate.go
  action/login/validate_test.go
  action/login_test.go
  go.mod
  go.sum
Labels: dependencies, enhancement

#136 feat(action): add config.Load() to load config file
  action/config/generate.go
  action/config/load.go
  action/config/load_test.go
  action/config/remove.go
  action/config/update.go
  cmd/vela-cli/main.go
Labels: feature

#138 refactor: finalize CLI for new design
  action/build_get.go
  action/build_restart.go
  action/build_view.go
  action/deployment_add.go
  action/deployment_get.go
  action/deployment_view.go
  action/hook_get.go
  action/hook_view.go
  action/log_get.go
  action/log_view.go
  action/repo_add.go
  action/repo_chown.go
  action/repo_get.go
  action/repo_remove.go
  action/repo_repair.go
  action/repo_update.go
  action/repo_view.go
  action/secret_add.go
  action/secret_get.go
  action/secret_remove.go
  action/secret_update.go
  action/secret_view.go
  action/service_get.go
  action/service_view.go
  action/step_get.go
  action/step_view.go
  cmd/vela-cli/load.go
  cmd/vela-cli/main.go
Labels: enhancement

#139 refactor: update addr to api.addr and token to api.token
  action/build_get_test.go
  action/build_restart_test.go
  action/build_view_test.go
  action/config/load_test.go
  action/config/remove_test.go
  action/config/update_test.go
  action/config_generate_test.go
  action/config_remove_test.go
  action/config_update_test.go
  action/deployment_add_test.go
  action/deployment_get_test.go
  action/deployment_view_test.go
  action/hook_get_test.go
  action/hook_view_test.go
  action/log_get_test.go
  action/log_view_test.go
  action/login_test.go
  action/repo_add_test.go
  action/repo_chown_test.go
  action/repo_get_test.go
  action/repo_remove_test.go
  action/repo_repair_test.go
  action/repo_update_test.go
  action/repo_view_test.go
  action/secret_add_test.go
  action/secret_get_test.go
  action/secret_remove_test.go
  action/secret_update_test.go
  action/secret_view_test.go
  action/service_get_test.go
  action/service_view_test.go
  action/step_get_test.go
  action/step_view_test.go
  internal/client/client_test.go
  internal/client/key.go
Labels: enhancement

#140 refactor: update engine to secret.engine and type to secret.type
  action/config/load.go
  action/config/load_test.go
  action/config/remove.go
  action/config/remove_test.go
  action/config/update.go
  action/config/update_test.go
  action/config_generate.go
  action/config_generate_test.go
  action/config_remove.go
  action/config_remove_test.go
  action/config_update.go
  action/config_update_test.go
  action/pipeline_generate.go
  action/secret_add.go
  action/secret_add_test.go
  action/secret_get.go
  action/secret_get_test.go
  action/secret_remove.go
  action/secret_remove_test.go
  action/secret_update.go
  action/secret_update_test.go
  action/secret_view.go
  action/secret_view_test.go
Labels: enhancement

#141 fix: ensure we mask password in prompt
  action/login/prompt.go
Labels: bug

#142 fix: parse client without token in login
  action/login.go
  internal/client/client.go
  internal/client/client_test.go
Labels: bug

#143 fix: references to variables
  action/repo/chown.go
  action/repo/remove.go
  action/repo/repair.go
  action/repo_chown.go
  action/repo_repair.go
  action/secret/remove.go
  go.mod
  go.sum
Labels: bug

#144 fix: load empty config file or values to prevent panics
  action/config/empty.go
  action/config/empty_test.go
  action/config/load.go
  action/config/load_test.go
Labels: bug

#145 feature(internal): add constants for CLI flags
  action/build_get.go
  action/build_restart.go
  action/build_view.go
  action/config/load.go
  action/config/remove.go
  action/config/update.go
  action/config_generate.go
  action/config_remove.go
  action/config_update.go
  action/config_view.go
  action/deployment_add.go
  action/deployment_get.go
  action/deployment_view.go
  action/hook_get.go
  action/hook_view.go
  action/log_get.go
  action/log_view.go
  action/login.go
  action/pipeline_generate.go
  action/repo_add.go
  action/repo_chown.go
  action/repo_get.go
  action/repo_remove.go
  action/repo_repair.go
  action/repo_update.go
  action/repo_view.go
  action/secret_add.go
  action/secret_get.go
  action/secret_remove.go
  action/secret_update.go
  action/secret_view.go
  action/service_get.go
  action/service_view.go
  action/step_get.go
  action/step_view.go
  cmd/vela-cli/main.go
  go.mod
  go.sum
  internal/client/client.go
  internal/client/key.go
  internal/internal.go
Labels: feature

#146 fix: load config for specific subcommands
  action/action.go
  action/build_get.go
  action/build_restart.go
  action/build_view.go
  action/completion_generate.go
  action/config/testdata/empty.yml
  action/deployment_add.go
  action/deployment_get.go
  action/deployment_view.go
  action/hook_get.go
  action/hook_view.go
  action/load.go
  action/load_test.go
  action/log_get.go
  action/log_view.go
  action/login.go
  action/repo_add.go
  action/repo_chown.go
  action/repo_get.go
  action/repo_remove.go
  action/repo_repair.go
  action/repo_update.go
  action/repo_view.go
  action/secret_add.go
  action/secret_get.go
  action/secret_remove.go
  action/secret_update.go
  action/secret_view.go
  action/service_get.go
  action/service_view.go
  action/step_get.go
  action/step_view.go
  cmd/vela-cli/log.go
  cmd/vela-cli/main.go
Labels: bug

#147 chore: update go mod for v0.5.0-rc1
  go.mod
  go.sum
  version/version.go
Labels: dependencies
