Repository go-vela/cli, pull requests merged in 2020-05, with the labels that each got.

#72 chore: update dependencies to v0.4.0
  go.mod
  go.sum
Labels: dependencies

#74 chore: update dependencies for release
  cmd/login.go
  go.mod
  go.sum
Labels: dependencies

#75 chore: update dependencies for release
  version/version.go
Labels: bug

#76 refactor: move main program to cmd/vela-cli
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  Dockerfile
  cmd/vela-cli/main.go
  makefile
  release.sh
Labels: enhancement

#77 feat: add action pkg shell
  action/action.go
  action/doc.go
Labels: feature

#79 feat: enable handling action output
  internal/doc.go
  internal/internal.go
  internal/output/doc.go
  internal/output/json.go
  internal/output/json_test.go
  internal/output/yaml.go
  internal/output/yaml_test.go
Labels: feature

#78 feat: add build action
  action/build/build.go
  action/build/build_test.go
  action/build/doc.go
  action/build/get.go
  action/build/get_command.go
  action/build/get_test.go
  action/build/restart.go
  action/build/restart_command.go
  action/build/restart_test.go
  action/build/view.go
  action/build/view_command.go
  action/build/view_test.go
Labels: feature

#83 chore: update for patch release v0.4.2
  go.mod
  go.sum
Labels: dependencies

#81 refactor: move build commands to action pkg
  action/action.go
  action/build/build.go
  action/build/build_test.go
  action/build/get.go
  action/build/restart.go
  action/build/view.go
  action/build_get.go
  action/build_get_test.go
  action/build_restart.go
  action/build_restart_test.go
  action/build_view.go
  action/build_view_test.go
Labels: enhancement

#85 chore: update for patch release v0.4.3
  go.mod
  go.sum
Labels: dependencies

#86 refactor(build): rename Build to Config
  action/build/build.go
  action/build/build_test.go
  action/build/get.go
  action/build/get_test.go
  action/build/restart.go
  action/build/restart_test.go
  action/build/validate.go
  action/build/validate_test.go
  action/build/view.go
  action/build/view_test.go
  action/build_get.go
  action/build_restart.go
  action/build_view.go
Labels: enhancement

#88 docs: divert bugs and features to community
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement

#87 perf(output): check for empty or nil value
  internal/output/default.go
  internal/output/default_test.go
  internal/output/json.go
  internal/output/json_test.go
  internal/output/yaml.go
  internal/output/yaml_test.go
Labels: enhancement

#89 chore: use internal/output pkg
  action/build/get.go
  action/build/restart.go
  action/build/view.go
Labels: enhancement

#90 feat: add deployment action
  action/deployment/add.go
  action/deployment/add_test.go
  action/deployment/deployment.go
  action/deployment/doc.go
  action/deployment/get.go
  action/deployment/get_test.go
  action/deployment/validate.go
  action/deployment/validate_test.go
  action/deployment/view.go
  action/deployment/view_test.go
Labels: feature

#91 feat: add repo action
  action/repo/add.go
  action/repo/add_test.go
  action/repo/chown.go
  action/repo/chown_test.go
  action/repo/doc.go
  action/repo/get.go
  action/repo/get_test.go
  action/repo/remove.go
  action/repo/remove_test.go
  action/repo/repair.go
  action/repo/repair_test.go
  action/repo/repo.go
  action/repo/update.go
  action/repo/update_test.go
  action/repo/validate.go
  action/repo/validate_test.go
  action/repo/view.go
  action/repo/view_test.go
Labels: feature
