Repository go-vela/cli, pull requests merged in 2020-01, with the labels that each got.

#40 chore: clean up linting for build commands
  cmd/build/get.go
  cmd/build/get_test.go
  cmd/build/restart_test.go
  cmd/build/util.go
  cmd/build/view_test.go
Labels: enhancement

#44 chore: use full apache license
  LICENSE
Labels: enhancement

#45 feat: add pagination for get cmds
  cmd/build/get.go
  cmd/build/get_test.go
  cmd/build/restart.go
  cmd/build/restart_test.go
  cmd/build/util.go
  cmd/build/view.go
  cmd/build/view_test.go
  cmd/repo/add.go
  cmd/repo/add_test.go
  cmd/repo/get.go
  cmd/repo/get_test.go
  cmd/repo/remove.go
  cmd/repo/remove_test.go
  cmd/repo/update.go
  cmd/repo/update_test.go
  cmd/repo/util.go
  cmd/repo/view.go
  cmd/repo/view_test.go
  cmd/secret/add.go
  cmd/secret/add_test.go
  cmd/secret/get.go
  cmd/secret/get_test.go
  cmd/secret/remove.go
  cmd/secret/update.go
  cmd/secret/update_test.go
  cmd/secret/util.go
  cmd/secret/view.go
  cmd/secret/view_test.go
  cmd/service/get.go
  cmd/service/get_test.go
  cmd/service/util.go
  cmd/service/view.go
  cmd/service/view_test.go
  cmd/step/get.go
  cmd/step/get_test.go
  cmd/step/util.go
  cmd/step/view.go
  cmd/step/view_test.go
  go.mod
  go.sum
Labels: feature

#47 fix(login): fix crash with using resp before error check
  cmd/login.go
Labels: bug
