Repository go-vela/cli, pull requests merged in 2020-08, with the labels that each got.

#148 fix: remove unusable global flags
  action/config/load.go
  action/load.go
  cmd/vela-cli/log.go
  cmd/vela-cli/main.go
Labels: bug

#152 enhancement(secret): add pipeline information with view
  action/secret/view.go
Labels: enhancement

#153 fix: loading config file for CLI commands
  action/config/load.go
  action/config/load_test.go
  cmd/vela-cli/load.go
  cmd/vela-cli/main.go
Labels: bug

#155 fix: ensure log data is outputted in string format
  action/log/get.go
  action/log/view.go
  version/version.go
Labels: bug

#156 refactor: make yaml output default for some view subcommands
  action/build_view.go
  action/deployment_view.go
  action/hook_view.go
  action/repo_view.go
  action/secret_get.go
  action/service_view.go
  action/step_view.go
Labels: enhancement

#159 fix: remove -h alias due to conflict with help
  action/hook_view.go
Labels: bug

#160 chore: update deps for release
  go.mod
  go.sum
Labels: dependencies

#161 chore: update version for v0.5.4 release
  version/version.go
Labels: dependencies
