Repository go-vela/cli, pull requests merged in 2021-01, with the labels that each got.

#174 feat: add shell for exec pipeline command
  action/action.go
  action/pipeline_exec.go
  cmd/vela-cli/compile.go
  cmd/vela-cli/exec.go
  cmd/vela-cli/expand.go
  cmd/vela-cli/main.go
  cmd/vela-cli/restart.go
Labels: feature

#186 feat(build): add cancel functionality
  action/action.go
  action/build/cancel.go
  action/build/cancel_test.go
  action/build_cancel.go
  action/build_cancel_test.go
  cmd/vela-cli/cancel.go
  cmd/vela-cli/main.go
  go.mod
  go.sum
Labels: feature

#188 feat(action): add logic to execute a pipeline
  action/pipeline/exec.go
  action/pipeline/pipeline.go
  action/pipeline_exec.go
  go.mod
  go.sum
Labels: feature

#191 feat: add a docs action
  DOCS.md
  action/docs/doc.go
  action/docs/docs.go
  action/docs/generate.go
  action/docs/generate_test.go
  action/docs/validate.go
  action/docs/validate_test.go
  action/docs_generate.go
  action/docs_generate_test.go
  cmd/vela-cli/generate.go
Labels: feature

#193 chore(deps): upgrade go-vela deps on v0.7.0-rc2
  go.mod
  go.sum
Labels: dependencies

#194 fix(pipeline): mount local volume in read-write mode
  action/pipeline/exec.go
  action/pipeline_exec.go
Labels: bug

#198 feat: add version information to executor
  action/pipeline/exec.go
  go.mod
  go.sum
Labels: feature

#199 feat: auth via PAT
  action/login.go
  action/login/login.go
  action/login/prompt.go
  go.mod
  go.sum
  internal/client/client.go
  internal/client/validate.go
Labels: feature
