Repository go-vela/cli, pull requests merged in 2021-05, with the labels that each got.

#234 feat(repo): allow setting the repo counter
  action/repo/add.go
  action/repo/add_test.go
  action/repo/repo.go
  action/repo/update.go
  action/repo_add.go
  action/repo_update.go
  go.mod
  go.sum
Labels: feature

#235 chore: upgrade go-vela deps on v0.8.0-rc1
  action/pipeline/exec.go
  go.mod
  go.sum
Labels: dependencies

#236 fix(login): return err when failing to connect to server
  action/login/login.go
Labels: bug

#237 chore: upgrade go-vela deps on v0.8.0-rc2
  go.mod
  go.sum
Labels: dependencies
