Repository go-vela/cli, pull requests merged in 2022-03, with the labels that each got.

#338 chore(dep): update containerd to 1.4.13
  go.mod
  go.sum
Labels: dependencies

#322 chore: add aliases to prevent redundancy
  command/build/cancel.go
  command/build/restart.go
  command/build/view.go
  command/deployment/view.go
  command/hook/view.go
  command/service/view.go
  command/step/view.go
Labels: enhancement

#341 fix: validating local pipelines
  action/pipeline/validate.go
  action/pipeline/validate_test.go
  go.mod
  go.sum
Labels: bug
